AllCops:
  TargetRubyVersion: 2.4.1
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 100
Metrics/ModuleLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
